// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VirTrade.Infrastructure.Persistence;

#nullable disable

namespace VirTrade.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260701202713_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("VirTrade.Core.Entities.ConfigMarche", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Valeur")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ConfigsMarche");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cle = "capital_initial",
                            Description = "Capital virtuel en USD à l'inscription",
                            Valeur = "100000"
                        },
                        new
                        {
                            Id = 2,
                            Cle = "tick_interval_ms",
                            Description = "Intervalle simulation prix en millisecondes",
                            Valeur = "3000"
                        },
                        new
                        {
                            Id = 3,
                            Cle = "volatilite_defaut",
                            Description = "Volatilité Brownian motion par défaut",
                            Valeur = "0.015"
                        },
                        new
                        {
                            Id = 4,
                            Cle = "market_impact_coeff",
                            Description = "Impact prix par tranche de 1000 actions tradées",
                            Valeur = "0.001"
                        });
                });

            modelBuilder.Entity("VirTrade.Core.Entities.HistoriquePrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("Volume")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId", "Timestamp");

                    b.ToTable("HistoriquesPrix");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Ordre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PrixLimite")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QuantiteExecutee")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SensOrdre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Statut")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TypeOrdre")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("Statut", "StockId");

                    b.ToTable("Ordres");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Portefeuille", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SoldeCash")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UtilisateurId")
                        .IsUnique();

                    b.ToTable("Portefeuilles");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("PortefeuilleId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("PrixMoyenAchat")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuantiteDetenue")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StockId");

                    b.HasIndex("PortefeuilleId", "StockId")
                        .IsUnique();

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("NomComplet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixActuel")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Volatilite")
                        .HasColumnType("decimal(5,4)");

                    b.HasKey("Id");

                    b.HasIndex("Symbole")
                        .IsUnique();

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NomComplet = "Apple Inc.",
                            PrixActuel = 150.00m,
                            Symbole = "AAPL",
                            Volatilite = 0.015m
                        },
                        new
                        {
                            Id = 2,
                            NomComplet = "Tesla Inc.",
                            PrixActuel = 250.00m,
                            Symbole = "TSLA",
                            Volatilite = 0.025m
                        },
                        new
                        {
                            Id = 3,
                            NomComplet = "Microsoft Corp.",
                            PrixActuel = 380.00m,
                            Symbole = "MSFT",
                            Volatilite = 0.012m
                        },
                        new
                        {
                            Id = 4,
                            NomComplet = "Amazon.com Inc.",
                            PrixActuel = 175.00m,
                            Symbole = "AMZN",
                            Volatilite = 0.018m
                        },
                        new
                        {
                            Id = 5,
                            NomComplet = "NVIDIA Corp.",
                            PrixActuel = 800.00m,
                            Symbole = "NVDA",
                            Volatilite = 0.030m
                        });
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BuyOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PrixExecution")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantite")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SellOrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StockId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BuyOrderId");

                    b.HasIndex("SellOrderId");

                    b.HasIndex("StockId", "ExecutedAt");

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.HistoriquePrix", b =>
                {
                    b.HasOne("VirTrade.Core.Entities.Stock", "Stock")
                        .WithMany("HistoriquePrix")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Ordre", b =>
                {
                    b.HasOne("VirTrade.Core.Entities.Stock", "Stock")
                        .WithMany("Ordres")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirTrade.Core.Entities.Utilisateur", "Utilisateur")
                        .WithMany("Ordres")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Stock");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Portefeuille", b =>
                {
                    b.HasOne("VirTrade.Core.Entities.Utilisateur", "Utilisateur")
                        .WithOne("Portefeuille")
                        .HasForeignKey("VirTrade.Core.Entities.Portefeuille", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Position", b =>
                {
                    b.HasOne("VirTrade.Core.Entities.Portefeuille", "Portefeuille")
                        .WithMany("Positions")
                        .HasForeignKey("PortefeuilleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VirTrade.Core.Entities.Stock", "Stock")
                        .WithMany("Positions")
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Portefeuille");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Trade", b =>
                {
                    b.HasOne("VirTrade.Core.Entities.Ordre", "BuyOrder")
                        .WithMany("BuyTrades")
                        .HasForeignKey("BuyOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirTrade.Core.Entities.Ordre", "SellOrder")
                        .WithMany("SellTrades")
                        .HasForeignKey("SellOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VirTrade.Core.Entities.Stock", "Stock")
                        .WithMany()
                        .HasForeignKey("StockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BuyOrder");

                    b.Navigation("SellOrder");

                    b.Navigation("Stock");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Ordre", b =>
                {
                    b.Navigation("BuyTrades");

                    b.Navigation("SellTrades");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Portefeuille", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Stock", b =>
                {
                    b.Navigation("HistoriquePrix");

                    b.Navigation("Ordres");

                    b.Navigation("Positions");
                });

            modelBuilder.Entity("VirTrade.Core.Entities.Utilisateur", b =>
                {
                    b.Navigation("Ordres");

                    b.Navigation("Portefeuille");
                });
#pragma warning restore 612, 618
        }
    }
}
